// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: friendship.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFriendship = `-- name: CreateFriendship :one
INSERT INTO friendships(
 user_id,
 friend_id,
 status
) VALUES (
  $1, $2, $3
) RETURNING id, user_id, friend_id, status, created_at, updated_at
`

type CreateFriendshipParams struct {
	UserID   pgtype.UUID
	FriendID pgtype.UUID
	Status   NullStatus
}

func (q *Queries) CreateFriendship(ctx context.Context, arg CreateFriendshipParams) (Friendship, error) {
	row := q.db.QueryRow(ctx, createFriendship, arg.UserID, arg.FriendID, arg.Status)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FriendID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFriendship = `-- name: DeleteFriendship :exec
DELETE FROM friendships
WHERE id = $1
`

func (q *Queries) DeleteFriendship(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteFriendship, id)
	return err
}

const getFriendship = `-- name: GetFriendship :one
SELECT id, user_id, friend_id, status, created_at, updated_at FROM friendships
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetFriendship(ctx context.Context, id pgtype.UUID) (Friendship, error) {
	row := q.db.QueryRow(ctx, getFriendship, id)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FriendID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNumberOfFriends = `-- name: GetNumberOfFriends :one
SELECT COUNT(*) FROM friendships
WHERE user_id = $1 AND status = 'accepted'
`

func (q *Queries) GetNumberOfFriends(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getNumberOfFriends, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getNumberOfPendingFriendRequests = `-- name: GetNumberOfPendingFriendRequests :one
SELECT COUNT(*) FROM friendships
WHERE friend_id = $1 AND status = 'pending'
`

func (q *Queries) GetNumberOfPendingFriendRequests(ctx context.Context, friendID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getNumberOfPendingFriendRequests, friendID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listFriendships = `-- name: ListFriendships :many
SELECT id, user_id, friend_id, status, created_at, updated_at FROM friendships
ORDER BY id
`

func (q *Queries) ListFriendships(ctx context.Context) ([]Friendship, error) {
	rows, err := q.db.Query(ctx, listFriendships)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Friendship
	for rows.Next() {
		var i Friendship
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FriendID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFriendship = `-- name: UpdateFriendship :one
UPDATE friendships
  set status = $2
WHERE id = $1
RETURNING id, user_id, friend_id, status, created_at, updated_at
`

type UpdateFriendshipParams struct {
	ID     pgtype.UUID
	Status NullStatus
}

func (q *Queries) UpdateFriendship(ctx context.Context, arg UpdateFriendshipParams) (Friendship, error) {
	row := q.db.QueryRow(ctx, updateFriendship, arg.ID, arg.Status)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FriendID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
