// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: post.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts(
 wall_id,
 author,
 media_url,
 post_type
) VALUES (
  $1, $2, $3, $4
) RETURNING id, wall_id, author, media_url, post_type, is_highlighted, likes_count, is_deleted, created_at
`

type CreatePostParams struct {
	WallID   pgtype.UUID
	Author   pgtype.UUID
	MediaUrl pgtype.Text
	PostType NullPostType
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.WallID,
		arg.Author,
		arg.MediaUrl,
		arg.PostType,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.WallID,
		&i.Author,
		&i.MediaUrl,
		&i.PostType,
		&i.IsHighlighted,
		&i.LikesCount,
		&i.IsDeleted,
		&i.CreatedAt,
	)
	return i, err
}

const getPost = `-- name: GetPost :one
SELECT id, wall_id, author, media_url, post_type, is_highlighted, likes_count, is_deleted, created_at FROM posts
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPost(ctx context.Context, id pgtype.UUID) (Post, error) {
	row := q.db.QueryRow(ctx, getPost, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.WallID,
		&i.Author,
		&i.MediaUrl,
		&i.PostType,
		&i.IsHighlighted,
		&i.LikesCount,
		&i.IsDeleted,
		&i.CreatedAt,
	)
	return i, err
}

const listPosts = `-- name: ListPosts :many
SELECT id, wall_id, author, media_url, post_type, is_highlighted, likes_count, is_deleted, created_at FROM posts
ORDER BY id
`

func (q *Queries) ListPosts(ctx context.Context) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.WallID,
			&i.Author,
			&i.MediaUrl,
			&i.PostType,
			&i.IsHighlighted,
			&i.LikesCount,
			&i.IsDeleted,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
